# Generated by Django 5.0 on 2023-12-06 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='Контакты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateField(null=True, verbose_name='Дедлайн')),
                ('dc', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель задачи')),
                ('projects', models.ManyToManyField(related_name='tasks', to='core.project', verbose_name='проекты')),
                ('students', models.ManyToManyField(related_name='tasks', to='core.student', verbose_name='студент')),
            ],
        ),
    ]
